version: '3'
services:
  automation:
      image: ansible
      tty: true
      stdin_open: true
      build:
        context: ./
      networks:
        - net
      volumes:
        - /etc/secrets/:/etc/secrets/
        - /var/log/ansible:/var/log/ansible
        - ./config:/etc/config
        - /Users/kevin/network_services/cnicc-customer-onboarding:/project
        - ./compose_script.sh:/project/compose_script.sh
      command: bash /project/compose_script.sh
  remote_host_ssh:
    image: remote_host-ssh
    build:
      context: ./ssh-enabled-ubuntu
networks:
   net:
